### PR TITLE
Update org.gtk.Gtk3theme.Yaru-dark.json

### PR DESCRIPTION
**Pull request by clobrano**
Aligned Yaru-dark at Yaru master

### CODE REVIEW

**Comment by TingPing** [comment]
Planning on fixing it?

**Comment by clobrano** [comment]
Sure, just I don't know (yet) how to test locally before push

**Comment by TingPing** [comment]
Install `flatpak-builder` then `flatpak-buidler builddir org.gtk.Gtk3theme.Yaru-dark.json --force-clean --user --install`

**Comment by clobrano** [comment]
Awesome, thanks!

**Comment by clobrano** [comment]
One issue was that the `gtk.css` file was compiled from folder `Yaru/gtk-3.0`, while in the meantime we added support to `gtk-3.20`, so that in the tree there is a new folder `gtk-3.20`. I assumed I could fix this replacing, in the JSON, all the occurencies of `gtk-3.0` with `gtk-3.20`, however in this way `sassc` build fails with error

  configure: error: unable to find libsass library (use --with-libsass?)

`--with-libsass` points to `/usr/share/runtime/share/themes/Yaru/gtk-3.20` 
and, according to the logs, `libtool` installed libsass into `/usr/share/runtime/share/themes/Yaru/gtk-3.20/lib`

so, I don't really get what I'm missing, can you give me a hint?

**Comment by TingPing** [comment]
Do the reverse, replace 3.20 in the yaru with 3.0.

**Comment by clobrano** [comment]
Do you mean in yaru repo? I can't do that

**Comment by TingPing** [comment]
You can do it in the package.

**Comment by clobrano** [comment]
While I look into flatpak docs for the best practice, why is this necessary? Are flatpak themes bounded to `gtk-3.0` folder?

**Pull request closed without merging**
